export const queryKeys = {
  me: ["me"] as const,
  challenges: (filters: Record<string, unknown>) => ["challenges", filters] as const,
  challenge: (id: string) => ["challenge", id] as const,
  challengeSimilar: (id: string) => ["challenge", id, "similar"] as const,
  challengeRouting: (id: string) => ["challenge", id, "routing"] as const,
  challengesMap: ["challenges", "map"] as const,
  universities: (filters: Record<string, unknown>) => ["universities", filters] as const,
  university: (id: string) => ["university", id] as const,
  industries: (filters: Record<string, unknown>) => ["industries", filters] as const,
  proposals: (filters: Record<string, unknown>) => ["proposals", filters] as const,
  projects: (filters: Record<string, unknown>) => ["projects", filters] as const,
  project: (id: string) => ["project", id] as const,
  milestones: (projectId: string) => ["project", projectId, "milestones"] as const,
  notifications: (unreadOnly: boolean) => ["notifications", unreadOnly] as const,
  comments: (entityType: string, entityId: string) => ["comments", entityType, entityId] as const,
  analyticsOverview: ["analytics", "overview"] as const,
  analyticsByDomain: ["analytics", "by-domain"] as const,
  analyticsByDistrict: ["analytics", "by-district"] as const,
  analyticsFunnel: ["analytics", "funnel"] as const,
  analyticsTimeseries: ["analytics", "timeseries"] as const,
  analyticsLeaderboard: ["analytics", "leaderboard"] as const,
  analyticsOutcomes: ["analytics", "outcomes"] as const,
  ipChain: ["ip", "verify-chain"] as const,
};
